package gui;

import people.Customer;

public class EditCustomerInfo extends javax.swing.JFrame {

    people.Customer theCustomer = new people.Customer();
    people.Customer theChangedCustomer = new people.Customer();
    String customerIDString = ManagerScreen.mas.jLabelCustomerID.getText();
    int customerID = Integer.parseInt(customerIDString);
    
    /**
     * Creates new form EditCustomerInfo
     */
    public EditCustomerInfo() {
        initComponents();
        
        theCustomer.search(customerID);
        theChangedCustomer.search(customerID);
        
        jTextFieldFirstName.setText(theCustomer.getFirstName());
        jTextFieldLastName.setText(theCustomer.getLastName());
        jTextFieldSSN.setText(theCustomer.getSSNumber());
        jTextFieldStreetAddress.setText(theCustomer.getStreetAddress());
        jTextFieldCity.setText(theCustomer.getCity());
        jTextFieldState.setText(theCustomer.getState());
        jTextFieldZip.setText(theCustomer.getZipCode());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSSN = new javax.swing.JTextField();
        jTextFieldStreetAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldState = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldZip = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jButtonEditCustomer = new javax.swing.JButton();
        jLabelEnterText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonCancel.setText("Cancel");
        jButtonCancel.setToolTipText("Return to Previous Screen");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Edit Customer Information");

        jLabel8.setText("Zip");

        jLabel7.setText("State");

        jTextFieldSSN.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldSSN.setToolTipText("Social Security Number");

        jTextFieldStreetAddress.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldStreetAddress.setToolTipText("Street Address");

        jLabel4.setText("SSN");

        jLabel3.setText("Last Name");

        jLabel6.setText("City");

        jLabel5.setText("Street Address");

        jLabel2.setText("First Name");

        jTextFieldFirstName.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldFirstName.setToolTipText("First Name");

        jTextFieldState.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldState.setToolTipText("State");

        jTextFieldCity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldCity.setToolTipText("City");
        jTextFieldCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCityActionPerformed(evt);
            }
        });

        jTextFieldZip.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldZip.setToolTipText("Zip Code");

        jTextFieldLastName.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldLastName.setToolTipText("Last Name");

        jButtonEditCustomer.setText("Edit Customer");
        jButtonEditCustomer.setToolTipText("Edit");
        jButtonEditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEditCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(53, 53, 53))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(90, 90, 90)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCity, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jTextFieldSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jTextFieldLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jTextFieldStreetAddress)
                            .addComponent(jTextFieldZip)
                            .addComponent(jTextFieldState)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabelEnterText, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEnterText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(247, 431));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonEditCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditCustomerActionPerformed

        theChangedCustomer.setFirstName(jTextFieldFirstName.getText());
        theChangedCustomer.setLastName(jTextFieldLastName.getText());
        theChangedCustomer.setSSN(jTextFieldSSN.getText());
        theChangedCustomer.setStreetAddress(jTextFieldStreetAddress.getText());
        theChangedCustomer.setCity(jTextFieldCity.getText());
        theChangedCustomer.setState(jTextFieldState.getText());
        theChangedCustomer.setZipCode(jTextFieldZip.getText());
        
        if((theCustomer.getFirstName()).equals(theChangedCustomer.getFirstName())
                && theCustomer.getLastName().equals(theChangedCustomer.getLastName())
                && theCustomer.getSSNumber().equals(theChangedCustomer.getSSNumber())
                && theCustomer.getStreetAddress().equals(theChangedCustomer.getStreetAddress())
                && theCustomer.getCity().equals(theChangedCustomer.getCity())
                && theCustomer.getState().equals(theChangedCustomer.getState())
                && theCustomer.getZipCode().equals(theChangedCustomer.getZipCode())){
            jLabelEnterText.setText("Enter A Change");
        }else{
            jLabelEnterText.setText("");
            
            theCustomer.print();
            
            if(theCustomer.getFirstName().equals(theChangedCustomer.getFirstName())){
                //Do Nothing
            }else{
                theCustomer.setFirstName(theChangedCustomer.getFirstName());
            }
            
            if(theCustomer.getLastName().equals(theChangedCustomer.getLastName())){
                //Do Nothing
            }else{
                theCustomer.setLastName(theChangedCustomer.getLastName());
            }
            
            if(theCustomer.getSSNumber().equals(theChangedCustomer.getSSNumber())){
                //Do Nothing
            }else{
                theCustomer.setSSN(theChangedCustomer.getSSNumber());
            }
            
            if(theCustomer.getStreetAddress().equals(theChangedCustomer.getStreetAddress())){
                //Do Nothing
            }else{
                theCustomer.setStreetAddress(theChangedCustomer.getStreetAddress());
            }
            
            if(theCustomer.getCity().equals(theChangedCustomer.getCity())){
                //Do Nothing
            }else{
                theCustomer.setCity(theChangedCustomer.getCity());
            }
            
            if(theCustomer.getState().equals(theChangedCustomer.getState())){
                //Do Nothing
            }else{
                theCustomer.setState(theChangedCustomer.getState());
            }
            
            if(theCustomer.getZipCode().equals(theChangedCustomer.getZipCode())){
                //Do Nothing
            }else{
                theCustomer.setZipCode(theChangedCustomer.getZipCode());
            }

            //Need to add the updated information to the database
            //theCustomer.delete();
            //theCustomer.add();
            
            theCustomer.print();
            
            dispose();
        }

    }//GEN-LAST:event_jButtonEditCustomerActionPerformed

    private void jTextFieldCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCustomerInfo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonEditCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEnterText;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldSSN;
    private javax.swing.JTextField jTextFieldState;
    private javax.swing.JTextField jTextFieldStreetAddress;
    private javax.swing.JTextField jTextFieldZip;
    // End of variables declaration//GEN-END:variables
}
